name: Run Lint and Test

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Install dependencies
        run: poetry install --no-root
      - name: Install statelint (Node.js ASL linter)
        run: npm install -g statelint
      - name: Compile Rust code
        run: make compile
      - name: Run lint
        run: make lint
      - name: Run tests
        run: poetry run pytest
